
version: 2
updates:
#  - package-ecosystem: "dotnet-sdk"
#    directory:
#      "/"
#    schedule:
#      interval: "daily"
#    ignore:
#      - dependency-name: "*"
#        update-types:
#          - "version-update:semver-major"
  - package-ecosystem: "nuget"
    directories:
      - "/WinCred/"
      - "/WinCred.Test/"
    schedule:
      interval: "daily"
