
version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory:
      "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directories:
      - "/WinCred/"
      - "/WinCred.Test/"
    schedule:
      interval: "daily"
